CREATE DATABASE IF NOT EXISTS bd_seguridad;
CREATE DATABASE IF NOT EXISTS bd_entrenadores;
CREATE DATABASE IF NOT EXISTS bd_pokedex;
CREATE DATABASE IF NOT EXISTS bd_torneos;
CREATE DATABASE IF NOT EXISTS bd_tienda;
CREATE DATABASE IF NOT EXISTS bd_medallas;
CREATE DATABASE IF NOT EXISTS bd_inventario;
CREATE DATABASE IF NOT EXISTS bd_centropk;